apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestor
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: data-ingestor
  template:
    metadata:
      labels:
        app: data-ingestor
    spec:
      containers:
      - name: data-ingestor
        image: data-ingestor
        # This will make sure that the local image is used
        imagePullPolicy: Never
        ports:
        - containerPort: 81
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestor
spec:
  ports:
  - name: data-ingestorports
    protocol: TCP
    port: 81
    targetPort: 81
  selector:
    app: data-ingestor
