package nexraddata.service;

import java.util.HashMap;

import org.springframework.stereotype.Service;

@Service
public class RadarStationService {
	
	HashMap<String, String> stations = new HashMap<String, String>();
	
	public RadarStationService() {
		stations.put("Birmingham","kbmx");
		stations.put("E. Alabama", "kmxx");
		stations.put("Fort Rucker", "keox");
		stations.put("Mobile", "kmob");
		stations.put("Nrn. Alabama", "khtx");
		stations.put("Bethel", "pabc");
		stations.put("Biorka Is.", "pacg");
		stations.put("Fairbanks", "papd");
		stations.put("Kenai", "pahg");
		stations.put("King Salmon", "pakc");
		stations.put("Middleton Is.", "paih");
		stations.put("Nome", "paec");
		stations.put("Pedro Dome", "papd");
		stations.put("Sitka", "pacg");
		stations.put("Flagstaff","kfsx");
		stations.put("Phoenix","kiwa");
		stations.put("Tucson","kemx");
		stations.put("Yuma","kyux");
		stations.put("Little Rock","klzk");
		stations.put("W. Ark./Ft. Smith","ksrx");
		stations.put("Beale AFB","kbbx");
		stations.put("Edwards AFB","keyx");
		stations.put("Eureka","kbhx");
		stations.put("Hanford","khnx");
		stations.put("Los Angeles","kvtx");
		stations.put("Sacramento","kdax");
		stations.put("San Diego","knkx");
		stations.put("San Francisco","kmux");
		stations.put("San Joaquin Vly.","khnx");
		stations.put("Santa Ana Mtns","ksox");
		stations.put("Vandenberg AFB","kvbx");
		stations.put("Denver/Boulder","kftg");
		stations.put("Grand Junction","kgjx");
		stations.put("Pueblo","kpux");
		stations.put("Dover AFB","kdox");
		stations.put("Eglin AFB","kevx");
		stations.put("Jacksonville","kjax");
		stations.put("Key West","kbyx");
		stations.put("Melbourne","kmlb");
		stations.put("Miami","kamx");
		stations.put("NW Florida","kevx");
		stations.put("Tallahassee","ktlh");
		stations.put("Tampa Bay Area","ktbw");
		stations.put("Atlanta","kffc");
		stations.put("Moody AFB","kvax");
		stations.put("Peachtree City","kffc");
		stations.put("Robins AFB","kjgx");
		stations.put("Andersen AFB","pgua");
		stations.put("Kauai","phki");
		stations.put("Kohala","phkm");
		stations.put("Molokai","phmo");
		stations.put("South Shore","phwa");
		stations.put("Boise","kcbx");
		stations.put("Pocatello","ksfx");
		stations.put("Central IL","kilx");
		stations.put("Chicago","klot");
		stations.put("Evansville","kvwx");
		stations.put("Indianapolis","kind");
		stations.put("Nrn. Indiana","kiwx");
		stations.put("Des Moines","kdmx");
		stations.put("Quad Cities","kdvn");
		stations.put("Dodge City","kddc");
		stations.put("Goodland","kgld");
		stations.put("Topeka","ktwx");
		stations.put("Wichita","kict");
		stations.put("Fort Cambell","khpx");
		stations.put("Jackson","kjkl");
		stations.put("Louisville","klvx");
		stations.put("Paducah","kpah");
		stations.put("Fort Polk","kpoe");
		stations.put("Lake Charles","klch");
		stations.put("New Orleans","klix");
		stations.put("Shreveport","kshv");
		stations.put("Caribou","kcbw");
		stations.put("Portland","kgyx");
		stations.put("Baltimore","klwx");
		stations.put("Boston","kbox");
		stations.put("Detroit","kdtx");
		stations.put("Gaylord","kapx");
		stations.put("Grand Rapids","kgrr");
		stations.put("Marquette","kmqt");
		stations.put("Duluth","kdlh");
		stations.put("Minneapolis","kmpx");
		stations.put("Columbus AFB","kgwx");
		stations.put("Brandon/Jackson","kdgx");
		stations.put("Kansas City","keax");
		stations.put("Springfield","ksgf");
		stations.put("St. Louis","klsx");
		stations.put("Billings","kblx");
		stations.put("Glasgow","kggw");
		stations.put("Great Falls","ktfx");
		stations.put("Missoula","kmsx");
		stations.put("Hastings","kuex");
		stations.put("North Platte","klnx");
		stations.put("Omaha","koax");
		stations.put("Elko","klrx");
		stations.put("Las Vegas","kesx");
		stations.put("Reno","krgx");
		stations.put("Mt. Holly","kdix");
		stations.put("Albuquerque","kabx");
		stations.put("Cannon AFB","kfdx");
		stations.put("Holloman AFB","khdx");
		stations.put("Albany","kenx");
		stations.put("Binghamton","kbgm");
		stations.put("Buffalo","kbuf");
		stations.put("Montague","ktyx");
		stations.put("New York City","kokx");
		stations.put("Upton","kokx");
		stations.put("Durham","krax");
		stations.put("Morehead City","kmhx");
		stations.put("Raleigh","krax");
		stations.put("Wilmington","kltx");
		stations.put("Bismarck","kbis");
		stations.put("Grand Forks","kmvx");
		stations.put("Minot AFB","kmbx");
		stations.put("Cincinnati","kiln");
		stations.put("Cleveland","kcle");
		stations.put("Dayton","kiln");
		stations.put("Wilmington","kiln");
		stations.put("Frederick","kfdr");
		stations.put("Oklahoma City","ktlx");
		stations.put("Tulsa","kinx");
		stations.put("Vance AFB","kvnx");
		stations.put("Medford","kmax");
		stations.put("Pendleton","kpdt");
		stations.put("Portland","krtx");
		stations.put("Philadelphia","kdix");
		stations.put("Pittsburgh","kpbz");
		stations.put("State College","kccx");
		stations.put("Puerto Rico/V.I.","tjua");
		stations.put("Charleston","kclx");
		stations.put("Columbia","kcae");
		stations.put("Greenville","kgsp");
		stations.put("Spartanburg","kgsp");
		stations.put("Greer","kgsp");
		stations.put("Aberdeen","kabr");
		stations.put("Rapid City","kudx");
		stations.put("Sioux falls","kfsd");
		stations.put("Knoxville","kmrx");
		stations.put("Memphis","knqa");
		stations.put("Morristown","kmrx");
		stations.put("Nashville","kohx");
		stations.put("Tri Cities","kmrx");
		stations.put("Amarillo","kama");
		stations.put("Austin","kewx");
		stations.put("Brownsville","kbro");
		stations.put("Central Texas","kgrk");
		stations.put("Corpus Christi","kcrp");
		stations.put("Dallas","kfws");
		stations.put("Dyess AFB","kdyx");
		stations.put("El Paso","kepz");
		stations.put("Fort Worth","kfws");
		stations.put("Galveston","khgx");
		stations.put("Houston","khgx");
		stations.put("Laughlin AFB","kdfx");
		stations.put("Lubbock","klbb");
		stations.put("Midland/Odessa","kmaf");
		stations.put("San Angelo","ksjt");
		stations.put("San Antonio","kewx");
		stations.put("Cedar City","kicx");
		stations.put("Salt Lake City","kmtx");
		stations.put("Burlington","kcxx");
		stations.put("Blacksburg","kfcx");
		stations.put("Norfolk","kakq");
		stations.put("Richmond","kakq");
		stations.put("Roanoke","kfcx");
		stations.put("Sterling","klwx");
		stations.put("Wakefield","kakq");
		stations.put("Seattle","katx");
		stations.put("Spokane","kotx");
		stations.put("Tacoma","katx");
		stations.put("Langley Hill","klgx");
		stations.put("Washington","klwx");
		stations.put("Charleston","krlx");
		stations.put("Green Bay","kgrb");
		stations.put("La Crosse","karx");
		stations.put("Milwaukee","kmkx");
		stations.put("Cheyenne","kcys");
		stations.put("Riverton","kriw");
		stations.put("Kunsan","rkjk");
		stations.put("Camp Humphreys","rksg");
	}
	
	public String getStation(String city) {
		String station = stations.get(city);
		return station.toUpperCase();
	}

}
