apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-plotting
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: data-plotting
  template:
    metadata:
      labels:
        app: data-plotting
    spec:
      containers:
      - name: data-plotting
        image: data-plotting
        # This will make sure that the local image is used
        imagePullPolicy: Never
        ports:
        - containerPort: 82
---
apiVersion: v1
kind: Service
metadata:
  name: data-plotting
spec:
  ports:
  - name: data-plottingports
    protocol: TCP
    port: 82
    targetPort: 82
  selector:
    app: data-plotting