# docker-compose.yml

version: '3.4'
services:

  account-service:
    build: ./account-service
    image: account-service
    ports:
      - 5000:5000
    networks:
      - mern-app

  greetings-service:
    build: ./greetings-service
    image: greetings-service
    ports:
      - 5001:5001
    networks:
      - mern-app

  data-ingestor:
    build: ./data-ingestor
    image: data-ingestor
    ports:
      - 81:81
    networks:
      - mern-app
  
 # data-plotting:
 #   build: ./data-plotting
 #   image: data-plotting
 #   ports:
 #     - 82:82
 #   networks:
 #    - mern-app

  # radar-station:
  #   container_name: radar-station
  #   build: ./radar-station
  #   image: radar-station
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - mern-app

  mongo:
    image: "mongo:4.4-bionic"
    ports:
      - "27017:27017"
    networks:
      - mern-app
    # network_mode: host
    volumes:
      - mongo-data:/data/db

  gui:
    build: ./gui
    image: gui
    ports:
      - 3000:3000
    networks:
      - mern-app
  
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - 3001:3001
    depends_on:
      - 'mongo'
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
