# docker-compose.yml

version: '3.4'
services:

  account-service:
    build: ./account-service
    image: account-service
    ports:
      - 5000:5000

  greetings-service:
    build: ./greetings-service
    image: greetings-service
    ports:
      - 5001:5001

  data-ingestor:
    build: ./data-ingestor
    image: data-ingestor
    ports:
      - 81:81
  
  data-plotting:
    build: ./data-plotting
    image: data-plotting
    ports:
      - 82:82

  radar-station:
    build: ./radar-station
    image: radar-station
    ports:
      - 8080:8080

  mongodb:
    image : mongo
    volumes:
      - /mongodb/database:/data/db
    ports:
      - 27017:27017

  gui:
    build: ./gui
    image: gui
    ports:
      - 3000:3000
  
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - 3001:3001