# docker-compose.yml

version: '3.4'
services:

  account-service:
    build: ./account-service
    image: account-service
    ports:
      - 5000:5000
    networks:
      - ampersand-network

  greetings-service:
    build: ./greetings-service
    image: greetings-service
    ports:
      - 5001:5001
    networks:
      - ampersand-network

  data-ingestor:
    build: ./data-ingestor
    image: data-ingestor
    ports:
      - 81:81
    networks:
      - ampersand-network
  
  data-plotting:
    build: ./data-plotting
    image: data-plotting
    ports:
      - 82:82
    networks:
      - ampersand-network

  # radar-station:
  #   build: ./radar-station
  #   image: radar-station
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - ampersand-network

  mongo:
    image: "mongo:4.4-bionic"
    ports:
      - "27017:27017"
    networks:
      - ampersand-network
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_USERNAME=guest
    networks:
      - ampersand-network

  gui:
    build: ./gui
    image: gui
    ports:
      - 3000:3000
    networks:
      - ampersand-network
  
  api-gateway:
    build: ./api-gateway
    image: api-gateway
    ports:
      - 3001:3001
    depends_on:
      - 'mongo'
    networks:
      - ampersand-network

networks:
  ampersand-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local