GET http://localhost:3000/users

###

GET http://localhost:3000/users/61f624d24cd8c31c6faad539

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "apednekar",
    "reqRadar": "KJFK",
    "reqDateYYYY": "2019",
    "reqDateMM": "03",
    "reqDateDD": "01",
    "reqStartTimeHH": "10",
    "reqStartTimeMM": "40",
    "reqStartTimeSS": "09",
    "reqEndTimeHH": "14",
    "reqEndTimeMM": "25",
    "reqEndTimeSS": "01"
}

###

DELETE http://localhost:3000/users/61f9036bea114f86479b2d72