apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
spec:
  selector:
    matchLabels:
      app: gui
  template:
    metadata:
      labels:
        app: gui
    spec:
      containers:
      - name: gui
        image: gui
        # This will make sure that the local image is used
        imagePullPolicy: Never
      ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gui
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  type: LoadBalancer
  ports:
  - name: guiports
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: gui