GET http://localhost:3001/users

###

POST http://localhost:3001/users/name
Content-Type: application/json

{
    "username": "NikhilKamble"
}

###
PATCH  http://localhost:3001/users/62004ed297b8e6e1752f2b01
Content-Type: application/json

{
    "id": "62004ed297b8e6e1752f2b01",
    "aws_url":  "https://noaa-nexrad-level2.s3.amazonaws.com/2013/01/05/KLTX/KLTX20130105_000559_V06.gz",
    "aws_fname":  "KLTX20130105_000559_V06.gz",
    "cloud_url":  "https://res.cloudinary.com/airavata-ampersand/image/upload/v1644187349/KLTX20130105_000559_V06.gz.png"
}


###

GET http://localhost:3001/users/61ff6806dcfc66a37353d26f

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "username": "apednekar",
    "reqRadar": "KJFK",
    "reqDateYYYY": "2019",
    "reqDateMM": "03",
    "reqDateDD": "01",
    "reqStartTimeHH": "10",
    "reqStartTimeMM": "40",
    "reqStartTimeSS": "09",
    "reqEndTimeHH": "14",
    "reqEndTimeMM": "25",
    "reqEndTimeSS": "01"
}

###

DELETE http://localhost:3001/users/61f9036bea114f86479b2d72