apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-service
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: greetings-service
  template:
    metadata:
      labels:
        app: greetings-service
    spec:
      containers:
      - name: greetings-service
        image: greetings-service
        # This will make sure that the local image is used
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: greetings-service
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  type: NodePort
  ports:
  - name: greetingsserviceports
    protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30003
  selector:
    app: greetings-service