apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service
        image: account-service
        # This will make sure that the local image is used
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  # This is for local testing this will expose
  # service on a NAT'ed port
  type: NodePort
  ports:
  - name: accountserviceports
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    app: account-service